#!/usr/bin/env bash
# Regenerate docs/cli-reference.md from what the binary actually prints.
#
# Replaces `typer … utils docs`, which read the Python app's decorators. That
# generator described the source; this one describes the shipped binary, so the
# reference cannot claim a flag the CLI does not have.
#
#   bash parity/tools/gen_cli_reference.sh          # uses ./khub
#   KHUB=/path/to/khub bash parity/tools/gen_cli_reference.sh
#
# CI runs it and then `git diff --exit-code docs/cli-reference.md`, so a flag
# added without regenerating fails the build.
set -euo pipefail

REPO=$(cd "$(dirname "$0")/../.." && pwd)
KHUB="${KHUB:-$REPO/khub}"
OUT="$REPO/docs/cli-reference.md"

# Registration order, matching newRoot() in internal/cli/root.go — the order
# `khub --help` lists them in, so the reference reads the same way.
COMMANDS=(
  init upgrade status add get edit link unlink remove query search neighbors impact
  history validate check stale reindex viz serve backfill wire schema
  "schema types" "schema show" "schema edges" "schema base" "schema snapshot" "schema diff"
)

# COLUMNS is pinned so the panels wrap identically wherever this runs.
export COLUMNS=80 TTY_COMPATIBLE=0 NO_COLOR=1

{
  echo "# khub CLI reference"
  echo
  echo "Generated by \`parity/tools/gen_cli_reference.sh\` from \`khub … --help\`."
  echo "Do not edit by hand — regenerate instead."
  echo
  echo '```console'
  echo "\$ khub --help"
  "$KHUB" --help | sed -e 's/[[:space:]]*$//'
  echo '```'
  for cmd in "${COMMANDS[@]}"; do
    echo
    echo "## khub $cmd"
    echo
    echo '```console'
    echo "\$ khub $cmd --help"
    # shellcheck disable=SC2086 -- word splitting is intended for "schema show"
    "$KHUB" $cmd --help | sed -e 's/[[:space:]]*$//'
    echo '```'
  done
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
